global:
  scrape_interval: 15s

scrape_configs:
  - job_name: spring-boot
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
  - job_name: 'jmeter'
    static_configs:
      - targets: ['host.docker.internal:9270']